@Library("shared") _
simple{
    git_url="https://github.com/pus1234567/ex1"
    name="ex1"
    tag="latest"
    address="192.168.2.5:8082"
    repo="192.168.2.5:8082/repository/docker-images"
    username="admin"
}
